namespace PaladinsAPI.Enums {
	public enum Tier : int {
		[System.ComponentModel.DescriptionAttribute ("Unranked (Qualifying)")]
        Unranked = 0,
		[System.ComponentModel.DescriptionAttribute ("Bronze V")]
		BronzeV = 1,
		[System.ComponentModel.DescriptionAttribute ("Bronze IV")]
		BronzeIV = 2,
		[System.ComponentModel.DescriptionAttribute ("Bronze III")]
		BronzeIII = 3,
		[System.ComponentModel.DescriptionAttribute ("Bronze II")]
		BronzeII = 4,
		[System.ComponentModel.DescriptionAttribute ("Bronze I")]
		BronzeI = 5,
        [System.ComponentModel.DescriptionAttribute ("Silver V")]
		SilverV = 6,
        [System.ComponentModel.DescriptionAttribute ("Silver IV")]
		SilverIV = 7,
        [System.ComponentModel.DescriptionAttribute ("Silver III")]
		SilverIII = 8,
        [System.ComponentModel.DescriptionAttribute ("Silver II")]
		SilverII = 9,
        [System.ComponentModel.DescriptionAttribute ("Silver I")]
		SilverI = 10,
        [System.ComponentModel.DescriptionAttribute ("Gold V")]
		GoldV = 11,
        [System.ComponentModel.DescriptionAttribute ("Gold IV")]
		GoldIV = 12,
        [System.ComponentModel.DescriptionAttribute ("Gold III")]
		GoldIII = 13,
        [System.ComponentModel.DescriptionAttribute ("Gold II")]
		GoldII = 14,
        [System.ComponentModel.DescriptionAttribute ("Gold I")]
		GoldI = 15,
        [System.ComponentModel.DescriptionAttribute ("Platinum V")]
		PlatinumV = 16,
        [System.ComponentModel.DescriptionAttribute ("Platinum IV")]
		PlatinumIV = 17,
        [System.ComponentModel.DescriptionAttribute ("Platinum III")]
		PlatinumIII = 18,
        [System.ComponentModel.DescriptionAttribute ("Platinum II")]
		PlatinumII = 19,
        [System.ComponentModel.DescriptionAttribute ("Platinum I")]
		PlatinumI = 20,
        [System.ComponentModel.DescriptionAttribute ("Diamond V")]
		DiamondV = 21,
        [System.ComponentModel.DescriptionAttribute ("Diamond IV")]
		DiamondIV = 22,
        [System.ComponentModel.DescriptionAttribute ("Diamond III")]
		DiamondIII = 23,
        [System.ComponentModel.DescriptionAttribute ("Diamond II")]
		DiamondII = 24,
        [System.ComponentModel.DescriptionAttribute ("Diamond I")]
		DiamondI = 25,
        [System.ComponentModel.DescriptionAttribute ("Master")]
		Master = 26,
        [System.ComponentModel.DescriptionAttribute ("Grandmaster")]
		Grandmaster = 27
    }
}